directory = File.dirname(__FILE__)

require "#{directory}/../../vagrant"

VagrantMachine.defaults_include(
  'box' => VagrantWindowsDesktopMachine.defaults['box'],
  'provisioners' => {
    'chef_policyfile_tools' => {},
    'reload' => {},
    'chef_policyfile_extensions' => {
      'path' => "#{directory}/../../../lib/gusztavvargadr/chef/lib/gusztavvargadr/vagrant/samples/deployments/vagrant/Policyfile.extensions.rb",
    },
    'chef_policyfile' => {},
  }
)

VagrantProvider.defaults_include(
  'memory' => 8192,
  'cpus' => 4
)

VagrantDeployment.configure(directory)
