name 'gusztavvargadr_packer_hyperv_iso'
maintainer 'Gusztáv Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Packer Hyper-V ISO'
long_description 'Installs/Configures Packer Hyper-V ISO'
version '0.0.0'
