Vagrant.configure("2") do |config|
  config.vm.define "default", primary: true do |config_vm|
    config_vm.vm.box = "gusztavvargadr/ubuntu-server"
  end

  config.vm.define "2004-lts", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/ubuntu-server-2004-lts"
  end

  config.vm.provision "shell", inline: <<-EOH
    uname -a
    lsb_release -a
    lshw
  EOH
end
