load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config_vm_define config, "2404-lts", "ubuntu-server-2404-lts"
  config_vm_define config, "2404-lts-alias", "ubuntu-server"
  config_vm_define config, "2204-lts", "ubuntu-server-2204-lts"
  config_vm_define config, "2004-lts", "ubuntu-server-2004-lts"

  config.vm.provision "shell", inline: <<-EOH
    uname -a
    lsb_release -a

    lshw -short
    lscpu
    lsmem

    apt list --installed
  EOH
end
