name 'gusztavvargadr_packer_vs15p'
maintainer 'Gusztav Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Visual Studio 2010 Professional in Packer'
long_description 'Installs/Configures Visual Studio 2010 Professional in Packer'
version '0.1.0'

depends 'gusztavvargadr_packer_w'
depends 'gusztavvargadr_visual_studio'
