Vagrant.configure("2") do |config|
  config.vm.define "latest", primary: true do |config|
    config.vm.box = "gusztavvargadr/iis"
  end

  config.vm.define "windows-server", autostart: false do |config|
    config.vm.box = "gusztavvargadr/iis-windows-server"
  end

  config.vm.define "windows-server-core", autostart: false do |config|
    config.vm.box = "gusztavvargadr/iis-windows-server-core"
  end

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver
    systeminfo
    Get-ComputerInfo
    choco list -i

    dotnet --info
  EOH
end
