Vagrant.configure("2") do |config|
  config.vm.define "default", primary: true do |config_vm|
    config_vm.vm.box = "gusztavvargadr/iis"
  end

  config.vm.define "windows-server", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/iis-windows-server"
  end

  config.vm.define "windows-server-core", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/iis-windows-server-core"
  end

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver
    systeminfo
    dotnet --info
  EOH
end
