load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.define "latest", primary: true do |config|
    config.vm.box = "gusztavvargadr/iis"
  end

  config.vm.define "windows-server", autostart: false do |config|
    config.vm.box = "gusztavvargadr/iis-windows-server"
  end

  config.vm.define "windows-server-core", autostart: false do |config|
    config.vm.box = "gusztavvargadr/iis-windows-server-core"
  end

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver

    systeminfo
    Get-ComputerInfo

    powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
    choco list -i

    dotnet --info
  EOH
end
