Vagrant.configure(2) do |config|
  config.vm.guest = :windows
  config.vm.communicator = 'winrm'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.network :forwarded_port, guest: 3389, host: 33389, auto_correct: true
end
