trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: windows-11.24h2-enterprise.hyperv

stages:
  - template: ../../stages.yml
    parameters:
      sample: visual-studio
      image: 2022-community-windows-11
      provider: hyperv
