source 'https://supermarket.chef.io'

cookbook 'gusztavvargadr_packer_w16s', path: 'cookbooks/gusztavvargadr_packer_w16s'
cookbook 'gusztavvargadr_packer_w', path: 'cookbooks/gusztavvargadr_packer_w'
cookbook 'gusztavvargadr_windows', github: 'gusztavvargadr/chef', branch: 'feature/9-update-with-changes-from-packer', rel: 'cookbooks/gusztavvargadr_windows'
