local_directory = File.expand_path('../../../../chef/', __FILE__)
core_directory = local_directory

instance_eval(File.read("#{core_directory}/Berksfile.core.rb"))

gusztavvargadr_packer_cookbook 'w12r2s', local_directory
