name 'gusztavvargadr_packer_amazon_ebs'
maintainer 'Gusztáv Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Packer Amazon EBS'
long_description 'Installs/Configures Packer Amazon EBS'
version '0.0.0'
