trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: ubuntu-server.2204-lts-arm64.virtualbox

stages:
  - template: ../../stages.yml
    parameters:
      sample: ubuntu-desktop
      image: 2204-lts-xubuntu-arm64
      provider: virtualbox
      hostArchitecture: ARM64
