load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config_vm_define config, "latest", "sql-server"
  config_vm_define config, "2019-developer-windows-server", "sql-server-2019-developer-windows-server"
  config_vm_define config, "2019-developer-windows-server-core", "sql-server-2019-developer-windows-server-core"

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver

    systeminfo
    Get-ComputerInfo

    Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    choco list -i

    sqlcmd -Q "SELECT @@VERSION"
  EOH
end
