source 'https://supermarket.chef.io'

cookbook 'gusztavvargadr_packer_vs15p', path: 'cookbooks/gusztavvargadr_packer_vs15p'
cookbook 'gusztavvargadr_packer_w', path: 'cookbooks/gusztavvargadr_packer_w'
cookbook 'gusztavvargadr_visual_studio', github: 'gusztavvargadr/chef', branch: 'feature/9-update-with-changes-from-packer', rel: 'cookbooks/gusztavvargadr_visual_studio'
cookbook 'gusztavvargadr_windows', github: 'gusztavvargadr/chef', branch: 'feature/9-update-with-changes-from-packer', rel: 'cookbooks/gusztavvargadr_windows'
