load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.define "windows", autostart: false do |config|
    config.vm.box = "gusztavvargadr/docker-windows"

    config.vm.provision "shell", inline: <<-EOH
      cmd /c ver
      systeminfo
      Get-ComputerInfo
      choco list -i

      docker version
      docker compose version
    EOH
  end

  config.vm.define "community-windows-server", autostart: false do |config|
    config.vm.box = "gusztavvargadr/docker-community-windows-server"

    config.vm.provision "shell", inline: <<-EOH
      cmd /c ver
      systeminfo
      Get-ComputerInfo
      choco list -i

      docker version
      docker compose version
    EOH
  end

  config.vm.define "community-windows-server-core", autostart: false do |config|
    config.vm.box = "gusztavvargadr/docker-community-windows-server-core"

    config.vm.provision "shell", inline: <<-EOH
      cmd /c ver
      systeminfo
      Get-ComputerInfo
      choco list -i

      docker version
      docker compose version
    EOH
  end

  config.vm.define "linux", autostart: false do |config|
    config.vm.box = "gusztavvargadr/docker-linux"

    config.vm.provision "shell", inline: <<-EOH
      uname -a
      lsb_release -a
      lshw -short
      apt list --installed

      docker version
      docker compose version
    EOH
  end

  config.vm.define "community-ubuntu-server", autostart: false do |config|
    config.vm.box = "gusztavvargadr/docker-community-ubuntu-server"

    config.vm.provision "shell", inline: <<-EOH
      uname -a
      lsb_release -a
      lshw -short
      apt list --installed

      docker version
      docker compose version
    EOH
  end
end
