Vagrant.configure(2) do |config|
  config.vm.guest = :windows
  config.vm.communicator = 'winssh'
  config.winssh.shell = 'powershell'

  config.vm.provider 'hyperv' do |h|
    h.memory = 1024
    h.cpus = 1
    h.ip_address_timeout = 300
  end
end
