load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config_vm_define config, "2404-lts-ubuntu", "ubuntu-desktop-2404-lts"
  config_vm_define config, "2404-lts-ubuntu-arm64", "ubuntu-desktop-2404-lts", "arm64"
  config_vm_define config, "2404-lts-xubuntu", "xubuntu-desktop-2404-lts"
  config_vm_define config, "2404-lts-xubuntu-arm64", "xubuntu-desktop-2404-lts", "arm64"
  config_vm_define config, "2204-lts-ubuntu", "ubuntu-desktop-2204-lts"
  config_vm_define config, "2204-lts-ubuntu-arm64", "ubuntu-desktop-2204-lts", "arm64"
  config_vm_define config, "2204-lts-xubuntu", "xubuntu-desktop-2204-lts"
  config_vm_define config, "2204-lts-xubuntu-arm64", "xubuntu-desktop-2204-lts", "arm64"

  config_vm_define config, "2404-lts-ubuntu-alias", "ubuntu-desktop"
  config_vm_define config, "2404-lts-xubuntu-alias", "xubuntu-desktop"

  config.vm.provision "shell", inline: <<-EOH
    uname -a
    lsb_release -a

    lshw -short
    lscpu
    lsmem

    if [ "$(uname -m)" = "aarch64" ]; then
      if [ -f /home/vagrant/.vbox_version ]; then
        echo "VirtualBox Guest Additions are not supported on Ubuntu ARM64 guests."
      else
        if ! command -v vmware-toolbox-cmd >/dev/null; then
          echo "VMware guest tools are not installed."
          exit 1
        fi

        vmware-toolbox-cmd -v
      fi
    fi

    apt list --installed
  EOH
end
