load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.define "latest", primary: true do |config|
    config.vm.box = "gusztavvargadr/ubuntu-desktop"
  end

  config.vm.define "2004-lts-xfce", autostart: false do |config|
    config.vm.box = "gusztavvargadr/ubuntu-desktop-2004-lts-xfce"
  end

  config.vm.provision "shell", inline: <<-EOH
    uname -a
    lsb_release -a
    lshw -short
    apt list --installed
  EOH
end
