load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config_vm_define config, "2404-lts-ubuntu", "ubuntu-desktop-2404-lts"
  config_vm_define config, "2404-lts-ubuntu-alias", "ubuntu-desktop"
  config_vm_define config, "2404-lts-ubuntu-arm", "ubuntu-desktop-2404-lts"
  config_vm_define config, "2404-lts-xubuntu", "xubuntu-desktop-2404-lts"
  config_vm_define config, "2404-lts-xubuntu-arm", "xubuntu-desktop-2404-lts"
  config_vm_define config, "2204-lts-ubuntu", "ubuntu-desktop-2204-lts"
  config_vm_define config, "2204-lts-ubuntu-arm", "ubuntu-desktop-2204-lts"
  config_vm_define config, "2204-lts-xubuntu", "xubuntu-desktop-2204-lts"
  config_vm_define config, "2204-lts-xubuntu-arm", "xubuntu-desktop-2204-lts"

  config.vm.provision "shell", inline: <<-EOH
    uname -a
    lsb_release -a

    lshw -short
    lscpu
    lsmem

    apt list --installed
  EOH
end
