Vagrant.configure("2") do |config|
  config.vm.define "default", primary: true do |config_vm|
    config_vm.vm.box = "gusztavvargadr/docker-linux"
  end

  config.vm.define "community-ubuntu-server", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/docker-community-ubuntu-server"
  end

  config.vm.define "community-ubuntu-desktop", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/docker-community-ubuntu-desktop"
  end

  config.vm.provision "shell", inline: <<-EOH
    uname -a
    lsb_release -a
    lshw
    docker version
    docker compose version
  EOH
end
