name 'gusztavvargadr_packer_w16s'
maintainer 'Gusztáv Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Packer Windows Server 2016 Standard'
long_description 'Installs/Configures Packer Windows Server 2016 Standard'
version '0.0.0'

depends 'gusztavvargadr_packer_w'
depends 'gusztavvargadr_windows'
