trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: windows-server.2022-standard.vmware

stages:
  - template: ../../stages.yml
    parameters:
      sample: development-windows
      image: "2022"
      provider: vmware
