load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config_vm_define config, "2025", "kitchen-windows-2025"
  config_vm_define config, "2022", "kitchen-windows-2022"

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver

    systeminfo
    Get-ComputerInfo

    choco list -i

    chef-client --version
  EOH
end
