name 'gusztavvargadr_packer_iis'
maintainer 'Gusztav Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures IIS in Packer'
long_description 'Installs/Configures IIS in Packer'
version '0.1.0'

depends 'gusztavvargadr_packer_w'
depends 'gusztavvargadr_iis'
