trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: windows-11.25h2-enterprise.virtualbox

stages:
  - template: ../../stages.yml
    parameters:
      sample: kitchen-windows
      image: prototype-windows-11-25h2-enterprise
      provider: virtualbox
