trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: windows-server.2025-standard.vmware

stages:
  - template: ../../stages.yml
    parameters:
      sample: kitchen-windows
      image: "2025"
      provider: vmware
