load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.define "latest", primary: true do |config|
    config.vm.box = "gusztavvargadr/windows-10"
  end

  config.vm.define "22h2-enterprise", autostart: false do |config|
    config.vm.box = "gusztavvargadr/windows-10-22h2-enterprise"
  end

  config.vm.define "21h2-enterprise", autostart: false do |config|
    config.vm.box = "gusztavvargadr/windows-10-21h2-enterprise"
  end

  config.vm.define "21h2-enterprise-ltsc", autostart: false do |config|
    config.vm.box = "gusztavvargadr/windows-10-21h2-enterprise-ltsc"
  end

  config.vm.define "1809-enterprise-ltsc", autostart: false do |config|
    config.vm.box = "gusztavvargadr/windows-10-1809-enterprise-ltsc"
  end

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver
    systeminfo
    Get-ComputerInfo
    choco list -i
  EOH
end
