Vagrant.configure("2") do |config|
  config.vm.define "default", primary: true do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-10"
  end

  config.vm.define "22h2-enterprise", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-10-22h2-enterprise"
  end

  config.vm.define "22h2-enterprise-nocm", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-10-22h2-enterprise-nocm"
  end

  config.vm.define "21h2-enterprise", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-10-21h2-enterprise"
  end

  config.vm.define "21h1-enterprise", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-10-21h1-enterprise"
  end

  config.vm.define "21h2-enterprise-ltsc", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-10-21h2-enterprise-ltsc"
  end

  config.vm.define "1809-enterprise-ltsc", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-10-1809-enterprise-ltsc"
  end

  config.vm.define "insider-preview-enterprise", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-10-insider-preview-enterprise"
  end

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver
    systeminfo
  EOH
end
