load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.define "latest", primary: true do |config|
    config.vm.box = "gusztavvargadr/docker-windows"
  end

  config.vm.define "community-windows-server", autostart: false do |config|
    config.vm.box = "gusztavvargadr/docker-community-windows-server"
  end

  config.vm.define "community-windows-server-core", autostart: false do |config|
    config.vm.box = "gusztavvargadr/docker-community-windows-server-core"
  end

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver

    systeminfo
    Get-ComputerInfo

    Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    choco list -i

    docker version
    docker compose version
  EOH
end
