load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config_vm_define config, "latest", "docker-windows"
  config_vm_define config, "community-windows-server", "docker-community-windows-server"
  config_vm_define config, "community-windows-server-core", "docker-community-windows-server-core"

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver

    systeminfo
    Get-ComputerInfo

    Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    choco list -i

    docker version
    docker compose version
  EOH
end
