Vagrant.configure('2') do |config|
  config.vm.box = 'gusztavvargadr/w16s-vs10p'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provider 'hyperv' do |h|
    h.memory = 4096
    h.cpus = 2
    h.differencing_disk = true
    h.enable_virtualization_extensions = true
  end
end
