Vagrant.configure(2) do |config|
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.network :forwarded_port, guest: 3389, host: 53389, auto_correct: true
end
