load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.define "2204", autostart: false do |config|
    config.vm.box = "gusztavvargadr/kitchen-ubuntu-2204"
  end

  config.vm.provision "shell", inline: <<-EOH
    uname -a
    lsb_release -a

    lshw -short
    lscpu
    lsmem

    apt list --installed

    chef-client --version
  EOH
end
