load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config_vm_define config, "2404", "kitchen-ubuntu-2404"
  config_vm_define config, "2404-arm", "kitchen-ubuntu-2404"
  config_vm_define config, "2204", "kitchen-ubuntu-2204"
  config_vm_define config, "2204-arm", "kitchen-ubuntu-2204"

  config.vm.provision "shell", inline: <<-EOH
    uname -a
    lsb_release -a

    lshw -short
    lscpu
    lsmem

    apt list --installed

    chef-client --version
  EOH
end
