load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.define "latest", primary: true do |config|
    config.vm.box = "gusztavvargadr/visual-studio"
  end

  config.vm.define "2022-community-windows-11", autostart: false do |config|
    config.vm.box = "gusztavvargadr/visual-studio-2022-community-windows-11"
  end

  config.vm.define "2022-community-windows-10", autostart: false do |config|
    config.vm.box = "gusztavvargadr/visual-studio-2022-community-windows-10"
  end

  config.vm.define "2019-community-windows-11", autostart: false do |config|
    config.vm.box = "gusztavvargadr/visual-studio-2019-community-windows-11"
  end

  config.vm.define "2019-community-windows-10", autostart: false do |config|
    config.vm.box = "gusztavvargadr/visual-studio-2019-community-windows-10"
  end

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver

    systeminfo
    Get-ComputerInfo

    powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
    choco list -i

    dotnet --info
  EOH
end
