Vagrant.configure("2") do |config|
  config.vm.define "default", primary: true do |config_vm|
    config_vm.vm.box = "gusztavvargadr/visual-studio"
  end

  config.vm.define "2022-community-windows-server", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/visual-studio-2022-community-windows-server"
  end

  config.vm.define "2022-community-windows-11", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/visual-studio-2022-community-windows-11"
  end

  config.vm.define "2022-community-windows-10", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/visual-studio-2022-community-windows-10"
  end

  config.vm.define "2019-community-windows-server", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/visual-studio-2019-community-windows-server"
  end

  config.vm.define "2019-community-windows-11", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/visual-studio-2019-community-windows-11"
  end

  config.vm.define "2019-community-windows-10", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/visual-studio-2019-community-windows-10"
  end

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver
    systeminfo
    dotnet --info
  EOH
end
