Vagrant.configure("2") do |config|
  config.vm.define "windows-11", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/docker-desktop-windows-11"
  end

  config.vm.define "windows-10", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/docker-desktop-windows-10"
  end

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver
    systeminfo
    docker version
    docker compose version
  EOH
end
