name 'gusztavvargadr_packer_vs15p'
maintainer 'Gusztáv Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Packer Visual Studio 2015 Professional'
long_description 'Installs/Configures Packer Visual Studio 2015 Professional'
version '0.0.0'

depends 'gusztavvargadr_packer_w'
depends 'gusztavvargadr_vs'
