trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: ubuntu-server.2404-lts.virtualbox

stages:
  - template: ../../stages.yml
    parameters:
      sample: docker-linux
      image: community-ubuntu-server
      provider: virtualbox
