name 'gusztavvargadr_packer_vs15c'
maintainer 'Gusztav Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Visual Studio 2015 Community in Packer'
long_description 'Installs/Configures Visual Studio 2015 Communuity in Packer'
version '0.1.0'

depends 'gusztavvargadr_packer_w'
depends 'packer_windows'
depends 'packer_visual_studio'
