load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config_vm_define config, "2404", "development-ubuntu-2404"
  config_vm_define config, "2404-arm", "development-ubuntu-2404"
  config_vm_define config, "2204", "development-ubuntu-2204"
  config_vm_define config, "2204-arm", "development-ubuntu-2204"

  config.vm.provision "shell", inline: <<-EOH
    uname -a
    lsb_release -a

    lshw -short
    lscpu
    lsmem

    apt list --installed

    git --version

    dotnet --info

    docker version
    docker compose version
  EOH
end
