load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config_vm_define config, "2404", "development-ubuntu-2404"
  config_vm_define config, "2404-arm64", "development-ubuntu-2404", "arm64"
  config_vm_define config, "2204", "development-ubuntu-2204"
  config_vm_define config, "2204-arm64", "development-ubuntu-2204", "arm64"

  config.vm.provision "shell", inline: <<-EOH
    uname -a
    lsb_release -a

    lshw -short
    lscpu
    lsmem

    if [ "$(uname -m)" = "aarch64" ]; then
      if [ -f /home/vagrant/.vbox_version ]; then
        echo "VirtualBox Guest Additions are not supported on Ubuntu ARM64 guests."
      else
        if ! command -v vmware-toolbox-cmd >/dev/null; then
          echo "VMware guest tools are not installed."
          exit 1
        fi

        vmware-toolbox-cmd -v
      fi
    fi

    apt list --installed

    git --version

    dotnet --info

    docker version
    docker compose version
  EOH
end
