name 'gusztavvargadr_packer_iis'
maintainer 'Gusztáv Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Packer IIS'
long_description 'Installs/Configures Packer IIS'
version '0.0.0'

depends 'gusztavvargadr_packer_w'
depends 'gusztavvargadr_iis'
