name 'gusztavvargadr_packer_de'
maintainer 'Gusztáv Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Packer Docker Enterprise'
long_description 'Installs/Configures Packer Docker Enterprise'
version '0.0.0'

depends 'gusztavvargadr_packer_w'
depends 'gusztavvargadr_docker'
depends 'gusztavvargadr_windows'
