load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config_vm_define config, "2025", "development-windows-2025"
  config_vm_define config, "2022", "development-windows-2022"

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver

    systeminfo
    Get-ComputerInfo

    choco list -i

    git --version

    dotnet --info

    docker version
    docker compose version
  EOH
end
