name 'gusztavvargadr_packer_vs17c'
maintainer 'Gusztáv Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Packer Visual Studio 2017 Community'
long_description 'Installs/Configures Packer Visual Studio 2017 Community'
version '0.0.0'

depends 'gusztavvargadr_packer_w'
depends 'gusztavvargadr_docker'
depends 'gusztavvargadr_vs'
depends 'gusztavvargadr_windows'
