name 'gusztavvargadr_packer_w10e'
maintainer 'Gusztav Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Windows 10 Enterprise in Packer'
long_description 'Installs/Configures Windows 10 Enterprise in Packer'
version '0.1.0'

depends 'gusztavvargadr_packer_w'
depends 'gusztavvargadr_windows'
