load "#{File.dirname(__FILE__)}/../core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.define "latest", primary: true do |config|
    config.vm.box = "gusztavvargadr/windows-server"
  end

  config.vm.define "latest-core", autostart: false do |config|
    config.vm.box = "gusztavvargadr/windows-server-core"
  end
  
  config.vm.define "2022-standard", autostart: false do |config|
    config.vm.box = "gusztavvargadr/windows-server-2022-standard"
  end

  config.vm.define "2022-standard-core", autostart: false do |config|
    config.vm.box = "gusztavvargadr/windows-server-2022-standard-core"
  end

  config.vm.define "2019-standard", autostart: false do |config|
    config.vm.box = "gusztavvargadr/windows-server-2019-standard"
  end

  config.vm.define "2019-standard-core", autostart: false do |config|
    config.vm.box = "gusztavvargadr/windows-server-2019-standard-core"
  end

  config.vm.define "insider-preview-standard", autostart: false do |config|
    config.vm.box = "gusztavvargadr/windows-server-insider-preview-standard"
  end

  config.vm.define "insider-preview-standard-core", autostart: false do |config|
    config.vm.box = "gusztavvargadr/windows-server-insider-preview-standard-core"
  end

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver
    systeminfo
    Get-ComputerInfo
    choco list -i
  EOH
end
