Vagrant.configure("2") do |config|
  config.vm.define "default", primary: true do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-server"
  end

  config.vm.define "2022-standard", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-server-2022-standard"
  end

  config.vm.define "2022-standard-nocm", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-server-2022-standard-nocm"
  end

  config.vm.define "2019-standard", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-server-2019-standard"
  end

  config.vm.define "insider-preview-standard", autostart: false do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-server-insider-preview-standard"
  end

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver
    systeminfo
  EOH
end
