parameters:
  sample: ''
  image: ''
  provider: ''
  hostArchitecture: ''
  artifactHandoff: conventional
  vagrantCanonicalization: none

stages:
  - stage: native
    displayName: Native

    jobs:
      - template: ./jobs.yml
        parameters:
          sample: ${{ parameters.sample }}
          image: ${{ parameters.image }}
          provider: ${{ parameters.provider }}
          hostArchitecture: ${{ parameters.hostArchitecture }}
          artifactHandoff: ${{ parameters.artifactHandoff }}
          vagrantCanonicalization: ${{ parameters.vagrantCanonicalization }}
          build: native

  - stage: vagrant
    displayName: Vagrant

    jobs:
      - template: ./jobs.yml
        parameters:
          sample: ${{ parameters.sample }}
          image: ${{ parameters.image }}
          provider: ${{ parameters.provider }}
          hostArchitecture: ${{ parameters.hostArchitecture }}
          artifactHandoff: ${{ parameters.artifactHandoff }}
          vagrantCanonicalization: ${{ parameters.vagrantCanonicalization }}
          build: vagrant
