parameters:
  sample: ''
  image: ''
  provider: ''
  hostArchitecture: ''
  artifactTransferAgentOS: ''
  prototypeVirtualBoxNativeProducer: false
  prototypeVirtualBoxVagrantSparse: false
  artifactTransferBenchmark: false
  artifactTransferRepresentation: control
  artifactTransferSequence: ''

stages:
  - stage: native
    displayName: Native

    jobs:
      - template: ./jobs.yml
        parameters:
          sample: ${{ parameters.sample }}
          image: ${{ parameters.image }}
          provider: ${{ parameters.provider }}
          hostArchitecture: ${{ parameters.hostArchitecture }}
          artifactTransferAgentOS: ${{ parameters.artifactTransferAgentOS }}
          prototypeVirtualBoxNativeProducer: ${{ and(eq(parameters.prototypeVirtualBoxNativeProducer, true), eq(parameters.artifactTransferRepresentation, 'candidate')) }}
          prototypeVirtualBoxVagrantSparse: false
          artifactTransferBenchmark: ${{ parameters.artifactTransferBenchmark }}
          artifactTransferRepresentation: ${{ parameters.artifactTransferRepresentation }}
          artifactTransferSequence: ${{ parameters.artifactTransferSequence }}
          build: native

  - stage: vagrant
    displayName: Vagrant

    jobs:
      - template: ./jobs.yml
        parameters:
          sample: ${{ parameters.sample }}
          image: ${{ parameters.image }}
          provider: ${{ parameters.provider }}
          hostArchitecture: ${{ parameters.hostArchitecture }}
          artifactTransferAgentOS: ${{ parameters.artifactTransferAgentOS }}
          prototypeVirtualBoxNativeProducer: ${{ and(eq(parameters.prototypeVirtualBoxNativeProducer, true), eq(parameters.artifactTransferRepresentation, 'candidate')) }}
          prototypeVirtualBoxVagrantSparse: ${{ and(eq(parameters.prototypeVirtualBoxVagrantSparse, true), eq(parameters.artifactTransferRepresentation, 'candidate')) }}
          artifactTransferBenchmark: ${{ parameters.artifactTransferBenchmark }}
          artifactTransferRepresentation: ${{ parameters.artifactTransferRepresentation }}
          artifactTransferSequence: ${{ parameters.artifactTransferSequence }}
          build: vagrant
